name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 17 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git
        run: |
          git --version
          git describe

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build with Maven on JDK ${{ matrix.java }}
        run: mvn --batch-mode verify